### ISSUE TITLE
add_node & detach bugs

### ISSUE THREAD

**Issue by mikesaroka** [diy4hobby/DAL#1]
Фактически функция `dal_t*	dal_t::add_node(dal_t* node)` не добавляет ветку в структуру, а перемещает ее (новая память не выделяется). При этом при вызове `dal_delete()` для структуры из которой эту ветку переместили возникает исключение нарушение доступа к памяти. Происходит это потому, что функция `detach()` которую вызывает `add_node()` не обнуляет указатели на удаленные элементы.

**Comment by diy4hobby** [comment]
На счет перемещения - все правильно, так и задумано было.
На счет указателей - нужен пример. Такой код не выявляет ошибки:

	dalMemHooks_t	memHooks	= { dal_alloc_node, dal_alloc_data, dal_free_node, dal_free_data };
	dal_init(&memHooks);

	dal_t*		topObj			= dal_create();
	
	topObj->add_value("string_value", "Hello from DAL");
	topObj->add_value("int_value", 123456789);
	topObj->add_value("dbl_value", 10.987654321);

	dal_t*		nodeObj			= dal_create();
	nodeObj->add_value("test_node", 12345);

	dal_t*		node			= nodeObj->get_child("test_node");

	topObj->add_node(node);

	dal_delete(nodeObj);
	dal_delete(topObj);
@mikesaroka, если можешь, приведи свой код, на котором ошибка гарантированно воспроизводится.

**Comment by mikesaroka** [comment]
```
dalMemHooks_t	memHooks = { dal_alloc_node, dal_alloc_data, dal_free_node, dal_free_data };
dal_init(&memHooks);

dal_t* topObj = dal_create();
	
topObj->add_value("string_value", "Hello from DAL");
topObj->add_value("int_value", 123456789);
topObj->add_value("dbl_value", 10.987654321);
topObj->add_value("bool_value", true);

dal_t* chldObj = topObj->create_child("child1");
int		u8Arr[5]		= {50, 40, 30, 20, 10};
chldObj->add_array("uint8_array", u8Arr, 5);
chldObj->add_value("name", "param1");
chldObj->create_child("child2")->add_value("name2", "param2");
	
uint8_t		buf[4096] = { 0 };
uint32_t	len;
len = topObj->to_mpack(buf, sizeof(buf));

dal_delete(topObj);

dal_t* newObj = dal_create(); //new object to read from mpack
dal_t* copyObj = dal_create(); //test object for memory leaks 
	
// Making newObj not empty before using it for deserialize
newObj->add_value("string_value", "newObj string value");
newObj->add_value("int_value", 9999999);
newObj->add_value("dbl_value", 99.999999);
newObj->add_value("name", "param1");
newObj->create_child("child_node")->add_value("level2", "value2");

copyObj->add_node(newObj->get_child("child_node"));
cout << "Try to deserialize from MPACK:" << endl;
cout << "newObj size before: " << newObj->size() << endl;

dalResult_e	result = newObj->from_mpack(buf, sizeof(buf));
```

Попробуй вот этот. У меня при вызове from_mpack возникает 

> Вызвано исключение: нарушение доступа для чтения. **child** было 0xFFFFFFFFFFFFFFEF.

**Comment by mikesaroka** [comment]
Fixed
